name: Test Matrix

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    name: Test on Node ${{ matrix.node-version }} and MongoDB ${{ matrix.mongodb-version }}
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
        mongodb-version: ['5.0', '6.0', '7.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Packages
        run: npm ci

      - name: Run Lint
        run: npm run lint
    
      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Test
        run: npm run test
        env:
          CI: true
